//===- Dialect.h - VC dialect ----------------------------------------------===//
//
// Declares the `vc` dialect class. The class body (constructor, namespace,
// initialize hook) is supplied by VCDialect.h.inc, generated from VC.td.
// Op/type declarations are in Ops.h.
//
//===----------------------------------------------------------------------===//

#ifndef VC_DIALECT_VC_DIALECT_H
#define VC_DIALECT_VC_DIALECT_H

#include "mlir/IR/Dialect.h"

// Generated by mlir-tblgen (VC.td, -gen-dialect-decls).
#include "vc/Dialect/VC/VCDialect.h.inc"

#endif // VC_DIALECT_VC_DIALECT_H
