//===- Ops.h - VC dialect operations --------------------------------------===//
//
// Op declarations for the `vc` dialect, generated from VC.td.
//
//===----------------------------------------------------------------------===//

#ifndef VC_DIALECT_VC_OPS_H
#define VC_DIALECT_VC_OPS_H

#include "vc/Dialect/VC/Dialect.h"

// Generated by mlir-tblgen (VC.td).
#include "vc/Dialect/VC/VCOps.h.inc"

#endif // VC_DIALECT_VC_OPS_H
