//===- Ops.h - VC dialect operations --------------------------------------===//
//
// Op declarations for the `vc` dialect, generated from VC.td.
//
//===----------------------------------------------------------------------===//

#ifndef VC_DIALECT_VC_OPS_H
#define VC_DIALECT_VC_OPS_H

#include "vc/Dialect/VC/Dialect.h"

// MLIR infrastructure the generated op classes rely on.
#include "mlir/Bytecode/BytecodeImplementation.h"
#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

// Generated by mlir-tblgen (VC.td, -gen-enum-decls).
#include "VCEnumAttrs.h.inc"

// Generated by mlir-tblgen (VC.td). The .inc guards the op class bodies
// behind GET_OP_CLASSES, so define it here for consumers of Ops.h.
#define GET_OP_CLASSES
#include "VCOps.h.inc"
#undef GET_OP_CLASSES

#endif // VC_DIALECT_VC_OPS_H
