//===- ASTToGLSL.cpp - Emit GLSL compute shader from AST -----------------===//

#include "vc/Codegen/ASTToGLSL.h"

#include "vc/Frontend/AST.h"

#include "llvm/Support/raw_ostream.h"

using namespace vc;
using namespace llvm;

namespace {

class GLSLEmitter {
  raw_ostream &os;
  // The kernel function being emitted.
  const FunctionDecl *kernel = nullptr;
  // Track which params are pointers vs scalars to declare bindings.
  SmallVector<const ParamDecl *, 8> params;

public:
  GLSLEmitter(raw_ostream &o) : os(o) {}

  bool emit(const TranslationUnit &tu) {
    // Find the first __global__ function.
    const FunctionDecl *fn = nullptr;
    for (auto &d : tu.decls) {
      if (d->getNodeType() == ASTNode::NodeKind::FunctionDecl) {
        auto *f = static_cast<const FunctionDecl *>(d.get());
        if (f->deviceAttr == DeviceAttr::Global) { fn = f; break; }
      }
    }
    if (!fn) {
      os << "// no __global__ kernel found\n";
      return false;
    }
    kernel = fn;
    params.assign(fn->params.begin(), fn->params.end());

    emitHeader();
    emitBindings();
    emitBody();
    return true;
  }

private:
  // Map a VC builtin type to a GLSL scalar type string.
  const char *glslType(const Type *t) {
    if (!t) return "float";
    if (t->getKind() == TypeKind::Builtin) {
      switch (static_cast<const BuiltinType *>(t)->builtin) {
      case BuiltinTypeKind::Void: return "void";
      case BuiltinTypeKind::Bool: return "bool";
      case BuiltinTypeKind::Int32: case BuiltinTypeKind::UInt32: return "int";
      case BuiltinTypeKind::Int64: case BuiltinTypeKind::UInt64: return "int64_t";
      case BuiltinTypeKind::Float32: return "float";
      case BuiltinTypeKind::Float64: return "double";
      }
    }
    // pointer-to-T -> T (SSBO element type)
    if (t->getKind() == TypeKind::Pointer)
      return glslType(static_cast<const PointerType *>(t)->pointee);
    return "float";
  }

  void emitHeader() {
    os << "#version 460 core\n";
    os << "#extension GL_EXT_shader_explicit_arithmetic_types : enable\n";
    os << "// generated by vc (GLSL backend)\n";
    // Default workgroup size 32 (matches the demo's block size).
    os << "layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;\n\n";
  }

  void emitBindings() {
    // One SSBO binding per parameter, in declaration order. Pointer params
    // expose a runtime-sized array; scalar params expose a single value.
    // This mirrors the runtime, which binds every argument as a storage
    // buffer.
    for (unsigned i = 0; i < params.size(); ++i) {
      const ParamDecl *p = params[i];
      const char *ty = glslType(p->type);
      bool isPtr = p->type && p->type->getKind() == TypeKind::Pointer;
      os << "layout(set = 0, binding = " << i << ") buffer B" << i << " {\n";
      if (isPtr)
        os << "  " << ty << " " << p->name << "[];\n";
      else
        os << "  " << ty << " " << p->name << ";\n";
      os << "}\n;\n";
    }
    os << "\n";
  }

  void emitBody() {
    os << "void main() {\n";
    if (kernel->body &&
        kernel->body->getNodeType() == ASTNode::NodeKind::CompoundStmt) {
      auto *cs = static_cast<const CompoundStmt *>(kernel->body.get());
      for (auto &s : cs->statements)
        emitStmt(s.get(), 1);
    }
    os << "}\n";
  }

  void pad(unsigned n) { for (unsigned i = 0; i < n; ++i) os << "  "; }

  void emitStmt(const ASTNode *n, unsigned indent) {
    if (!n) return;
    switch (n->getNodeType()) {
    case ASTNode::NodeKind::CompoundStmt: {
      pad(indent); os << "{\n";
      for (auto &s : static_cast<const CompoundStmt *>(n)->statements)
        emitStmt(s.get(), indent + 1);
      pad(indent); os << "}\n";
      break;
    }
    case ASTNode::NodeKind::DeclStmt: {
      auto *d = static_cast<const DeclStmt *>(n)->decl;
      if (!d) break;
      pad(indent);
      os << glslType(d->type) << " " << d->name;
      if (d->init) { os << " = "; emitExpr(d->init.get()); }
      os << ";\n";
      break;
    }
    case ASTNode::NodeKind::ExprStmt: {
      pad(indent);
      if (auto *e = static_cast<const ExprStmt *>(n)->expr.get())
        emitExpr(e);
      os << ";\n";
      break;
    }
    case ASTNode::NodeKind::ReturnStmt:
      pad(indent); os << "return";
      if (auto *r = static_cast<const ReturnStmt *>(n)->value.get()) {
        os << " "; emitExpr(r);
      }
      os << ";\n";
      break;
    case ASTNode::NodeKind::IfStmt: {
      auto *iff = static_cast<const IfStmt *>(n);
      pad(indent); os << "if ("; emitExpr(iff->cond.get()); os << ") {\n";
      if (iff->thenStmt) emitStmt(iff->thenStmt.get(), indent + 1);
      pad(indent); os << "}\n";
      if (iff->elseStmt) {
        pad(indent); os << "else {\n";
        emitStmt(iff->elseStmt.get(), indent + 1);
        pad(indent); os << "}\n";
      }
      break;
    }
    default:
      break;
    }
  }

  void emitExpr(const ASTNode *n) {
    if (!n) { os << "/*null*/"; return; }
    switch (n->getNodeType()) {
    case ASTNode::NodeKind::IntegerLiteral:
      os << static_cast<const IntegerLiteral *>(n)->value;
      break;
    case ASTNode::NodeKind::FloatLiteral:
      os << static_cast<const FloatLiteral *>(n)->value;
      break;
    case ASTNode::NodeKind::DeclRefExpr:
      os << static_cast<const DeclRefExpr *>(n)->name;
      break;
    case ASTNode::NodeKind::BinaryExpr: {
      auto *b = static_cast<const BinaryExpr *>(n);
      os << "(";
      emitExpr(b->lhs.get());
      os << " " << binopStr(b->op) << " ";
      emitExpr(b->rhs.get());
      os << ")";
      break;
    }
    case ASTNode::NodeKind::UnaryExpr: {
      auto *u = static_cast<const UnaryExpr *>(n);
      os << unaryopStr(u->op);
      emitExpr(u->operand.get());
      break;
    }
    case ASTNode::NodeKind::IndexExpr: {
      auto *ie = static_cast<const IndexExpr *>(n);
      emitExpr(ie->base.get());
      os << "[";
      emitExpr(ie->index.get());
      os << "]";
      break;
    }
    case ASTNode::NodeKind::MemberAccessExpr: {
      // CUDA built-ins -> GLSL equivalents.
      auto *m = static_cast<const MemberAccessExpr *>(n);
      if (m->base &&
          m->base->getNodeType() == ASTNode::NodeKind::DeclRefExpr) {
        auto *base = static_cast<const DeclRefExpr *>(m->base.get());
        StringRef b = base->name;
        // gl_*InvocationID/WorkGroup* are uvec3; CUDA indices are int, so
        // wrap in int(...) to match the C-like semantics.
        if (b == "threadIdx") { os << "int(gl_LocalInvocationID." << m->member << ")"; return; }
        if (b == "blockIdx")  { os << "int(gl_WorkGroupID."     << m->member << ")"; return; }
        if (b == "blockDim")  { os << "int(gl_WorkGroupSize."   << m->member << ")"; return; }
        if (b == "gridDim")   { os << "int(gl_NumWorkGroups."   << m->member << ")"; return; }
      }
      emitExpr(m->base.get());
      os << "." << m->member;
      break;
    }
    case ASTNode::NodeKind::CallExpr: {
      auto *c = static_cast<const CallExpr *>(n);
      if (c->callee &&
          c->callee->getNodeType() == ASTNode::NodeKind::DeclRefExpr) {
        auto *ref = static_cast<const DeclRefExpr *>(c->callee.get());
        if (ref->name == "__syncthreads") { os << "barrier()"; return; }
        // TODO: user functions.
      }
      os << "/*call*/";
      break;
    }
    default:
      os << "/*?*/";
      break;
    }
  }

  const char *binopStr(BinaryOp op) {
    switch (op) {
    case BinaryOp::Add: return "+";
    case BinaryOp::Sub: return "-";
    case BinaryOp::Mul: return "*";
    case BinaryOp::Div: return "/";
    case BinaryOp::Assign: return "=";
    case BinaryOp::Eq: return "==";
    case BinaryOp::NEq: return "!=";
    case BinaryOp::Lt: return "<";
    case BinaryOp::Gt: return ">";
    case BinaryOp::Le: return "<=";
    case BinaryOp::Ge: return ">=";
    default: return "?";
    }
  }

  const char *unaryopStr(UnaryOp op) {
    switch (op) {
    case UnaryOp::Neg: return "-";
    case UnaryOp::Not: return "~";
    case UnaryOp::LNot: return "!";
    case UnaryOp::Deref: return "*";
    case UnaryOp::AddrOf: return "&";
    default: return "?";
    }
  }
};

} // namespace

bool vc::glsl::translateASTToGLSL(const TranslationUnit &tu,
                                  raw_ostream &os) {
  return GLSLEmitter(os).emit(tu);
}
